### ISSUE TITLE
Subject line defaults differ from other best practice guides

### ISSUE THREAD

**Issue by pkqk** [bkuhlmann/git-cop#1]
2 of the defaults for the subject line are different from the common style that many other proponents of good commit messages are pushing.

- The requirement for a subject to end with a period
- The subject being in past tense

The style many others are pushing for is present tense without a ending period in the message.

Here's a collection of most other opinions: https://chris.beams.io/posts/git-commit/

**Comment by bkuhlmann** [comment]
Thanks, yep, I'm aware of that discussion. It's not a pattern I've followed or taught in the various teams I've worked on. The main reason is because your Git history is, as the name implies, a history. When I look through the history of any project I've worked on, I'm looking at what has transgressed and frozen in time. It's the past, not the present. It makes more sense to read it this way.

There is another benefit to doing this this way, and I mention it in the [Commit Subject Prefix](https://github.com/bkuhlmann/git-cop#commit-subject-prefix) documentation. It's because, when practiced, this way, you gain the ability to have all of your commits bundled up as a nice change log since the last tag/release. I automate this via the [Milestoner](https://github.com/bkuhlmann/milestoner) gem. The Git Cop and Milestoner gems are basically companions to each other. Makes for a great workflow. You can see examples of the Git Cop and Milestoner tools put to use on this project by looks at the past releases:

- [v1.1.0](https://github.com/bkuhlmann/git-cop/releases/tag/v1.1.0)
- [v1.0.0](https://github.com/bkuhlmann/git-cop/releases/tag/v1.0.0)

None of those releases were written by hand, all generated (i.e. the changes, the signed tag, etc.) via Milestoner...and enforced by Git Cop.

This makes for a great workflow, automates the building of clean and consistent looking change logs, and can be used for reporting purposes for managers or higher ups if need be.

All of this said, you are free to customize Git Cop to you like as you definitely don't have to use the defaults. At the end of the day, it's best to be consistent. ...but I do encourage you to try it this way. :)

**Comment by robwise** [comment]
For those wanting to configure to use present-tense (albeit using the provided prefixes), here is how I configured it:

```
:commit_subject_prefix:
  :enabled: true
  :severity: :error
  :includes:
    - 'Fix '
    - 'Add '
    - 'Update '
    - 'Remove '
    - 'Refactor '
```

I actually personally like it without periods so I want to enforce that the commit ends in a word character so I configured like this:

```
:commit_subject_suffix:
  :enabled: true
  :severity: :error
  :includes:
    - "\\w"
```

The error messages were even written in such a way that they pick up the non-default way you configured the rule so your colleagues will easily see how to resolve a failed cop.
