### ISSUE TITLE
Update gitcop to install commit-msg git hook

### ISSUE THREAD

**Issue by Gowiem** [bkuhlmann/git-cop#15]
## Overview
I installed this gem and haven't used it yet, because I keep forgetting to run the police function. This got me thinking that the police call needs to run after each commit or even stop a bad commit from taking place. Looking into the viability of that it looks like git hooks have a `commit-msg` hook which receives the commit. It'd be great to have an option to install this hook into the CWD's git project and it just becomes an existing part of the project flow forcing the user to fix their message before they commit. 

Here is the info on the `commit-msg` hook: 
> The commit-msg hook takes one parameter, which again is the path to a temporary file that contains the commit message written by the developer. If this script exits non-zero, Git aborts the commit process, so you can use it to validate your project state or commit message before allowing a commit to go through. In the last section of this chapter, We’ll demonstrate using this hook to check that your commit message is conformant to a required pattern.

That is taken from [customizing git hooks](https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks).

I'd happy to take a crack at this if this is something the project maintainers would like implemented.

**Comment by bkuhlmann** [comment]
Hey Matt, thanks. Yeah, I'm interested in this but am hesitant to maintain any special Git Hook customization because each developer's configuration is different. For example, I use a [global Git Hook configuration](https://github.com/bkuhlmann/dotfiles/tree/master/home_files/.git_template/hooks). More specifically, my [Git Commit Message Hook](https://github.com/bkuhlmann/dotfiles/blob/master/home_files/.git_template/hooks/commit-msg.tt) uses a pure Bash configuration which I plan to switch out once I finish work on the [severity issue](https://github.com/bkuhlmann/git-cop/issues/6).

I generally try to discourage developers from maintaining any special Git Hook per project configuration since they are hard to maintain. Sometimes they are necessary but, again, it depends on the project.

I was thinking of adding some helpful tips and tricks regarding Git Hooks to the README in the next release. Would that be sufficient instead?

**Comment by bkuhlmann** [comment]
Resolved in this [pull request](https://github.com/bkuhlmann/git-cop/pull/19).
