### ISSUE TITLE
Make the configuration file local to the project

### ISSUE THREAD

**Issue by Ana06** [bkuhlmann/git-cop#3]
Having the configuration file in `~/.config/git-cop/configuration.yml` is not practical. When having a project in Github you can add this file to Travis to run there when having a new PR, so it is fine in this sense. But if someone what to run the cop locally to avoid sending a PR with wrong commits it is not possible as he won't have locally the configuration file.

You also can not have different configurations for different projects in your computer.

Why not having a file called something like `.git-cop.yml` in the project? If it is not there then it can use the one in `~/.config/git-cop/configuration.yml`, just to keep the current behaviour. :thinking:

**Comment by bkuhlmann** [comment]
Hey Ana, thanks for the feedback.

Actually, Git Cop defaults to a global configuration but there is nothing stopping you from having a configuration per project, multiple directories, etc. This is all configurable via the XDG environment variables. Check out the [README Configuration](https://github.com/bkuhlmann/git-cop#configuration) section for details.

**Comment by Ana06** [comment]
But isn't all this too complicate? I was thinking about how to make it simpler :thinking:

**Comment by bkuhlmann** [comment]
Well, not really, but open to suggestions. Most people use tools like [direnv](https://direnv.net), [dotenv](https://github.com/bkeepers/dotenv), etc. to define custom settings per project. That's what I do. It's a one-line entry and you're done.

The important aspect of a XDG configuration that it keeps all of your dotfiles within a `.config` folder rather than cluttering up your `$HOME` or project directory.

**Comment by Ana06** [comment]
Ok, then let's close this

**Comment by deivid-rodriguez** [comment]
For what it's worth, I agree with @Ana06 here.

Projects should be able to have a project specific configuration that it's used by default if present. For example, you have a `.rubocop.yml` file in this repo. In my opinion, it would not be a good user experience if I everyone wanted to contribute to this repo needed to configure `direnv` to tell `rubocop` to read this file instead of its default configuration, just to get the code style right.

I mean it's great that you can configure the library so that you don't clutter your home folder or the root of your repo with configuration files, but in my opinion this is independent from providing a local configuration default location.

**Comment by bkuhlmann** [comment]
@deivid-rodriguez Thanks. In re-reading all of this, what is being requested here is to default priority to the following:

1. `<local project path>/.config/git-cop/configuration.yml`
1. `$HOME/.config/test/configuration.yml`

That is outside the scope of this project but is something that might worth supporting via the [Runcom](https://github.com/bkuhlmann/runcom) project since Git Cop uses that gem to manage configurations. I'll investigate this more. As long as this doesn't violate the XDG specification this might work. If so, this project would only need to update to the latest Runcom version to get the benefits.

**Comment by deivid-rodriguez** [comment]
Well, @Ana06 initially requested `<local project path>/.git-cop.yml`. I think the specfic path and its configurability is less important than actually providing and documenting _a_ default path _inside_ the project. In my opinion this is an important feature for every minimally configurable CLI project. As a user, I don't really mind if this is implemented in external gem, sounds like that makes the most sense for this project :+1:.

Thanks for considering and for your project!

**Comment by bkuhlmann** [comment]
@deivid-rodriguez Sounds good, I've got this on my next action list to investigate further now.

@Ana06 Sorry for the confusion on this. It wasn't until I re-read Open SUSE PR associated with this issue that I had a better example of what was going on here. Somehow I missed reading through that PR after this issue was initially closed.

**Comment by bkuhlmann** [comment]
:information_source: I've got a [Runcom release branch](https://github.com/bkuhlmann/runcom/compare/release) with working code that solves this issue not only for this project for several other CLI gems. The branch is still in flux but work necessary for supporting this workflow is done. The only change to this project will be upgrading to the new [Runcom](https://github.com/bkuhlmann/runcom) gem and you'll get the benefits immediately. :tada:

These changes will be rolled out with the release Ruby 2.6 around or a little after Christmas. So expect a major release under the 🎄 this year!

**Comment by robwise** [comment]
Confirmed this now works, just place your config file in your project at `.config/git-cop/configuration.yml` and it git-cop picks it up without me even needing to install the runcom gem or anything explicitly.
