### ISSUE TITLE
Support for branches that are not master in Travis

### ISSUE THREAD

**Issue by Ana06** [bkuhlmann/git-cop#42]
Currently Travis only support master as branch. :sob:

**Comment by Ana06** [comment]
No, this was never supported. It only works in the branch is called master.

**Comment by bkuhlmann** [comment]
I might be confused but Git Cop calculates the feature branch by looking for the value of `TRAVIS_BRANCH` or `TRAVIS_PULL_REQUEST_BRANCH`. It's not expected to be `master` but any appropriately named feature branch. Would you be able to explain the problem more and/or steps to recreate? I'm not sure I see what the issue is yet.

**Comment by bkuhlmann** [comment]
Was not able to reproduce any erroneous behavior on Circle CI or Travis CI using a feature branch. Closing due to lack of feedback.
