### ISSUE TITLE
Add commit body metadata cop.

### ISSUE THREAD

**Issue by Ana06** [bkuhlmann/git-cop#8]
In a project I am working in, we have tags in the commit message, something like:

`[api][webui] Change something in api and webui`

`[api] Change that only affect api`

What about a cop for ensuring that all commit have at least one tag. It should **not** to be enabled by default, as probably most projects don't have tags and to have a `whitelist` with the allowed tasks.

**Comment by bkuhlmann** [comment]
Yeah, that's an interesting idea. Do you use these in the commit subjects or the bodies? These tags, or metadata, should live within the body as much as possible. Much like how `[ci skip]` can be added to a body to skip a build (like a documentation update or something).

How are you using these tags? Are you using a reporting tool to do something with the tags and group commits by tag?

If a cop was introduced to check for these tags it would probably need a regular expression pattern to account for tags that get added but are not in the whitelist *but* look like a tag. That or the position of the tags would need to be at the end of the body. For example:

```
Example subject line.

Example body...

[ci skip]
```

**Comment by Ana06** [comment]
The tags are in the commit body always at the beginning, as the idea is to make more visible what part of the app is being changed without having to read the whole description.
But I guess once this is implemented, it would hurt make it configurable, in case someone else want to put then at the end.

**Comment by bkuhlmann** [comment]
Ah, good. I'd love to keep them at the end if at all possible. To me, that's metadata that doesn't need to be read immediately. Useful to have but even better if some other tool is being used to do analysis on it. I always look for the body to explain *why* the commit is important as it helps give me context before diving into the code diff.

**Comment by Ana06** [comment]
@bkuhlmann 

> Ah, good. I'd love to keep them at the end if at all possible.

Well, if I make it configurable, so the tags can be at the beginning or at the end, this shouldn't be a problem, right? I mean:

### OPTION 1
```
[ci skip] Example subject line.

Example body...
```
### OPTION 2
```
Example subject line.

Example body...

[ci skip]
```

 In order words, if I send a PR for this cop with the tags being configurable to be at the beginning or at the end, would you be fine with it?

**Comment by bkuhlmann** [comment]
Hmm, I really like Option 2. It's elegant and clean. I've seen tags used as subject prefixes before but never liked that style because it forces the reader to sift through metadata before getting to the actual content. It's important that the commit remain readable.

I really like this format:

```
<subject - what the commit is about>

<body - why the commit is necessary>

<metadata - various tags, etc. that categorize the commit>
```

The metadata should always be at the bottom. This keeps the commit clean, and human readable first and foremost. It allows for additional tools to consume the metadata for static analysis. This could be useful for tools, like Milestoner, when building release notes.

This also gives the commit a clear structure without too many options. It'll also keep the implementation simple by not having to check for metadata in multiple locations.

What do you think?

BTW, should tags always be in this format?

`[name]`

It always starts and ends with `[`, `]`? Is the body of the tag always a word or phrase? Any special characters restrictions within the tag name?

**Comment by Ana06** [comment]
@bkuhlmann but the thing is that in the project I am working on they need to be in the commit subject. For example, we have the frontend and the backend (two different applications) in the same repository. They are even written in different languages. So, that means that a developer working in the frontend is not interested at all in the commits with the `[backend]` tag. That's one of the reason why they have to be in the subject. Also, it is already done like that for years, so even if we wanted to change this, it would be impossible.

What would be the problem in supporting **both**, tags at the begging of the subject or at the end of the commit message and making it configurable? So, you could disable or enable option 2 in your projects and I could enable option 1. And everybody happy :smile: I am not trying to say that option1 is better than option2. I get your point, it is just that in the project I am working only option1 can be used.

Regarding the tags. My idea is that the tags are in a whitelist, to avoid that you can write whatever you want. In the practice we are only using 6 tags. And about the format, we use [name1][name2][name3], but again we could have [name1][name2][name3] and [name1, name2, name3] and then allow that everybody configure it as he wants.


To be able to add `git-cop` in my project I would need it to support this cop with option1. I would be up to send a PR, with all configuration options to make it also useful for you/other people.

**Comment by bkuhlmann** [comment]
Hmm, that is interesting regarding legacy support. Retrofitting this gem to support legacy projects will make this harder to maintain and downgrade it being effective in pushing projects forward to higher standards, I'm afraid.

This isn't actually an issue with the gem but an issue with the way the company was organized for you, sadly.

That said, you can make the existing implementation work for your situation. :smile: Why not add the tags to the whitelist of the [Commit Subject Prefix](https://github.com/bkuhlmann/git-cop#commit-subject-prefix) cop? This'll give you the ability to solve your needs for the allows subject lines (i.e. Option 1) and we can implement this feature strictly, for Option 2.

What do you think?

**Comment by bkuhlmann** [comment]
Regarding the format of the tags (i.e. Option 2). Let me do a little research first. I'm wondering if they should be strictly enforced as `[tag]`? Maybe `<tag>` or something else entirely. Let me get back to you on that. We might want to also ensure they they are space delimited. Example:

`[one] [two] [three]`

Rather than:

`[one][two][three]`

The space delimitation could be nice as it would make easier for downstream analytics tools.

**Comment by Ana06** [comment]
@bkuhlmann 

> That said, you can make the existing implementation work for your situation. :smile: Why not add the tags to the whitelist of the Commit Subject Prefix cop? This'll give you the ability to solve your needs for what is allowed in your subject lines (i.e. Option 1) and we can implement this feature, strictly, for Option 2.
> 
> What do you think?

That's actually a good idea, with one problem, the whitelist would get too long as I will need something like:

```
[one] Fix
[two] Fix
[three] Fix
[one] Change
[two] Change
[three] Change
[one] Refactor
[two] Refactor
[three] Refactor
....
```

What about allowing to use regular expression in the white list? That would be really cool! :heart_eyes: I'll open a new issue as this is not necessary related with the tags. This would solve my problem so feel free to close this issue, or keep it if you still want to have tags in the format you proposed! :wink:

**Comment by bkuhlmann** [comment]
Ha, OK. Yeah, I'm going to close this for now. I'm not saying this isn't worth doing, just that I want to study more use cases first. For example, another options I've explored in the past and am thinking about again due to the discussion above is leveraging [Git Notes](https://git-scm.com/docs/git-notes).

Anyway, for now, I'm going to close this issue in favor of more research.
